# Generated by Django 3.2.8 on 2021-10-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome do paciente')),
                ('cpf', models.CharField(max_length=250, verbose_name='Informe seu CPF ')),
                ('email', models.CharField(blank=True, max_length=250, null=True, verbose_name='E-mail')),
                ('celular', models.CharField(max_length=250, verbose_name='Núm. celular')),
            ],
            options={
                'verbose_name': 'cadastro',
                'verbose_name_plural': 'cadastro',
            },
        ),
    ]
